### ISSUE TITLE
MongoDB Issue on Apple M2 Silicon Chip

### ISSUE THREAD

**Issue by nawalnew** [nsarrazin/serge#10]
Hello,

can someone please help to set up the Docker image on my Mac with M2 Chip.
https://github.com/bitnami/containers/issues/14169
This solution seems not to work. 

Would be great if a Solution comes up.

Thank you

**Comment by jsonsmth** [comment]
I had the same issue on my Mac with M1 chip. I installed MongoDB locally on my Mac using Homebrew and updated the .env file to point to the local host to connect to MongoDB. Here are some links that might be helpful:

[https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-os-x/](https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-os-x/)

[https://stackoverflow.com/questions/65357744/how-to-install-mongodb-on-apple-m1-chip](https://stackoverflow.com/questions/65357744/how-to-install-mongodb-on-apple-m1-chip)

Here's the updated MongoDB connection string in my .env file:

`DATABASE_URL=mongodb://docker.for.mac.host.internal:27017/lms`

**Comment by nsarrazin** [comment]
Oh interesting. Unfortunately I can't replicate this since I don't have a mac.

Could one of you try replacing this line in the docker compose file
https://github.com/nsarrazin/serge/blob/b4c329286c8ce611ddcad2301aecfff09ae580fd/docker-compose.yml#L17
by 
```
    image: mongo
```

and let me know if it works ?

**Comment by kells1986** [comment]
OK, I think it might be working!

```
mongodb:
    image: mongo:6.0.4-jammy
    ports:
      - "27017"
    volumes:
      - data:/data/db
```

I'm not seeing any errors, but I've clicked "start new chat" and it's hanging.

**Comment by nawalnew** [comment]
Thank you all very much. 
@kells1986 Solution works. Thank you very much!!

I just cant chose a model, but this seems to have another problem.

**Comment by nawalnew** [comment]
Thank you very much. I am excited to try it.
