### ISSUE TITLE
LLAMA binary will sometimes just crash and produce no logs.

### ISSUE THREAD

**Issue by IngwiePhoenix** [nsarrazin/serge#105]
### Bug description

I have been playing around with this for a few hours now and it has been a lot of fun! Getting to use 20 out of my 24 cores (R9 3900X) and a good bunch of my 32GB of RAM has been entertaining, for sure!

However, even after increasing WSL's resource limits, LLAMA will still sometimes just crash.

### Steps to reproduce

1. Enable WSL2, Install Docker, enable wsl2 backend.
2. Follow readme to build and start the container.
3. Download 7b and 7b-native.
4. Have a few interactions with the model.
5. Observe forever spinning circle.
6. `wsl -d docker-desktop apk add htop`
7. `wsl -d docker-desktop htop` in another window.
8. Try to send a "Continue" message.
9. In `htop`: Observe `llama` starting and seemingly spinning up as all 20 threads increase usage.
10. Immediately after, the process and usage disappear.
11. Check `docker-compose logs` and find no output.

(I wouldn't be surprised if it printed at least an error to `stderr`...)

### Environment Information

Docker: Docker version 20.10.23, build 7155243
OS: Windows 10 22h2 (Build 19045.2788)
CPU: AMD Ryzen 9 3900X
RAM: 32GB @ 2133Mhz

`.wslconfig`:
```
[wsl2]
memory=20G
processors=20
```

### Screenshots

Infinite spinner:
![image](https://user-images.githubusercontent.com/2893716/228393784-c5a56d32-d853-42df-9a65-f5506ed0a2a9.png)

Sadly I don't know how to make a gif screenshot of just how fast the process dies... Sorry.

### Relevant log output

```shell
None, which is the odd part. o.o
```

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by IngwiePhoenix** [comment]
Retested with the updated llama.cpp master update in the Dockerfile - it still takes an angry nap :)

Suggestion: Option (env variable?) to print stdout/stderr upon task completion. Should enable better debugging.

**Comment by gaby** [comment]
@IngwiePhoenix Can you try the latest image?
