### ISSUE TITLE
All I get is "Loading"

### ISSUE THREAD

**Issue by seyo-IV** [nsarrazin/serge#107]
Everything installed and running, no errors or stuff.

After every send message I only get Loading 

I'm using a raspberry pi

**Comment by M1xel** [comment]
If you are really using a raspberry pi have you looked at the system load?
The models require a hefty amount of CPU performance and the 7B Model (smallest one) is requiring about ~6 GB ram do you have that in your Raspberry Pi?

**Comment by voarsh2** [comment]
Lol. No way in hell are you running this on a Pi....
I wouldn't even try using CPU bound with modern era CPU's...

**Comment by M1xel** [comment]
> Unfortunately I only have 1 GPU and I'm using it for gaming.....

Currently Llama.cpp doesnt support running it over GPU if I remember right only the CPU is used so that should not be a problem

**Comment by gaby** [comment]
@seyo-IV any updates?
