### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by VanHallein** [nsarrazin/serge#108]
### Bug description

I pulled the latest docker image available and downloaded the 7B and 7b-native model. However, when starting the chat conversation, I simply get a [Errno 2] No such file or directory response in the chat. I exactly used the command line documented to pull and start the Docker container.

### Steps to reproduce

Installing and running the latest docker container, using:

docker run -d -v weights:/usr/src/app/weights -v datadb:/data/db/ -p 8008:8008 ghcr.io/nsarrazin/serge:latest

### Environment Information

Docker version 23.0.2, build 569dd73
Linux debian 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
Debian 10.3 x64

### Screenshots

![image](https://user-images.githubusercontent.com/124934907/228599847-3fc1eaa3-1e74-40f7-b7a3-7ebed0c0fa5e.png)

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by nsarrazin** [comment]
Can you try deleting your chat history database with `docker volume rm serge_datadb` or `docker volume rn datadb` and try again ?

**Comment by VanHallein** [comment]
Nope, didn't really help. Is there anything I need to do on the host machine? I mean, I simply pulled the container and started it. Is there anything else to it? Should I docker build the container myself?

**Comment by mcmiv413** [comment]
I’m getting the same error, this is in the logs

`llama.cpp build info: 
I UNAME_S:  Linux
I UNAME_P:  x86_64
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -Wno-unused-function -pthread -mavx -mavx2 -msse3
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -pthread
I LDFLAGS:  
I CC:       cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
I CXX:      g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

cc  -I.              -O3 -DNDEBUG -std=c11   -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -Wno-unused-function -pthread -mavx -mavx2 -msse3   -c ggml.c -o ggml.o
ggml.c: In function 'ggml_vec_dot_q4_1':
ggml.c:1965:72: warning: binary constants are a C2X feature or GCC extension
 1965 |         const __m256 cross_scales = _mm256_blend_ps( scale_0, scale_1, 0b10101010 );
      |                                                                        ^~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-linux-gnu/11/include/immintrin.h:99,
                 from ggml.c:182:
ggml.c: In function 'ggml_vec_dot_q4_0':
/usr/lib/gcc/x86_64-linux-gnu/11/include/fmaintrin.h:63:1: error: inlining failed in call to 'always_inline' '_mm256_fmadd_ps': target specific option mismatch
   63 | _mm256_fmadd_ps (__m256 __A, __m256 __B, __m256 __C)
      | ^~~~~~~~~~~~~~~
ggml.c:1815:15: note: called from here
 1815 |         acc = _mm256_fmadd_ps( d, p, acc );
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-linux-gnu/11/include/immintrin.h:99,
                 from ggml.c:182:
/usr/lib/gcc/x86_64-linux-gnu/11/include/fmaintrin.h:63:1: error: inlining failed in call to 'always_inline' '_mm256_fmadd_ps': target specific option mismatch
   63 | _mm256_fmadd_ps (__m256 __A, __m256 __B, __m256 __C)
      | ^~~~~~~~~~~~~~~
ggml.c:1815:15: note: called from here
 1815 |         acc = _mm256_fmadd_ps( d, p, acc );
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-linux-gnu/11/include/immintrin.h:99,
                 from ggml.c:182:
/usr/lib/gcc/x86_64-linux-gnu/11/include/fmaintrin.h:63:1: error: inlining failed in call to 'always_inline' '_mm256_fmadd_ps': target specific option mismatch
   63 | _mm256_fmadd_ps (__m256 __A, __m256 __B, __m256 __C)
      | ^~~~~~~~~~~~~~~
ggml.c:1815:15: note: called from here
 1815 |         acc = _mm256_fmadd_ps( d, p, acc );
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:226: ggml.o] Error 1
mv: cannot stat 'main': No such file or directory `

**Comment by willjasen** [comment]
> I’m getting the same error, this is in the logs

Your logs are similar to #48

**Comment by VanHallein** [comment]
I am seeing kind of a pattern here. It is indicated that the compiling is failing when the machine is some sort of VM. I am not able to run the host Linux natively. @mcmiv413 mcmiv413 I am assuming you're running it in some sort of VBox or VMWare?

**Comment by mcmiv413** [comment]
Sorry missed this earlier, yes it is a VM running Ubuntu on a windows host using virtualbox

**Comment by VanHallein** [comment]
Ok, I got Serge finally up and running. I build the docker image using the Dockerfile. However, I made some changes in the Dockerfile by also apt-get installing the cmake. I then also changed the code in compile.sh to work with cmake. After these changes, the whole docker image builds and runs fine (but very slow). 

![image](https://user-images.githubusercontent.com/124934907/228965421-2ad7966c-379b-4d1b-98a4-4c39810c83ca.png)

I am running this in a VBox Image on a Win10 host.

**Comment by gamersalpha** [comment]
> However, I made some changes in the Dockerfile by also apt-get installing the cmake. I then also changed the code in compile.sh to work with cmake. After these changes, the whole docker image b

Hello i got the same error

and i m not on a virtual machine

can give us the Dockerfiles please ?

thanks*ù

**Comment by gaby** [comment]
@gamersalpha The image can be download with: `ghcr.io/nsarrazin/serge:latest`

Running:

```bash
docker run -d -v weights:/usr/src/app/weights -v datadb:/data/db/ -p 8008:8008 ghcr.io/nsarrazin/serge:latest
```
