### ISSUE TITLE
Websocket error

### ISSUE THREAD

**Issue by nawalnew** [nsarrazin/serge#11]
Ive got it to work locally on my M2 with the help of the issue before.

But I got stuck with the Websocket.
When I ask something, than it loads endless. 

**WebSocket connection to 'ws://localhost:8008/' failed: There was a bad response from the server.**

Ive tried in chrome and Safari.

**Comment by kells1986** [comment]
I can't get to the chat page. After I click "Start a New Chat" it just hangs forever before I eventually get a 504 error. This is on my M1 machine, tried firefox and chrome

**Comment by nawalnew** [comment]
Sorry @kells1986 , I didnt run into this issue on my mac. 
But look in your dev tools what is wrong there. Maybe the same underlying websocket issue.

**Comment by kells1986** [comment]
I'm seeing the same issue now too:

```
WebSocket connection to 'ws://localhost:8008/' failed: 
Direct websocket connection fallback. Check out https://vitejs.dev/config/server-options.html#server-hmr to remove the previous connection error.
```

**Comment by kells1986** [comment]
Working! Thanks, this is awesome!

**Comment by nsarrazin** [comment]
I'm gonna close this now, if you still have issues let me know and I will reopen it!

**Comment by dylancl** [comment]
Hi,

Hopefully you don't mind me posting in a closed issue, but I'm still facing the same issue on the latest commit on main running on a M1 MacBook. I can see the request successfully reaches the API, but it's infinitely stuck on loading (and still showing the WebSocket connection failed error message). 

Am I doing something wrong here? 🤔 

![SCR-20230322-vdt](https://user-images.githubusercontent.com/14956708/227044211-2e66a50e-3ec1-4a42-a2e7-925bb2f5fb27.png)

**Comment by nsarrazin** [comment]
@dylancl No problem, if you have an issue I want to help!

Just as a last check, can you try rebuilding with `docker compose build --no-cache` ? if the issue persists, I'll re-open it no problem.

**Comment by vnktsh** [comment]
I'm getting the same error too. Stuck on LOADING.

Running on Mac M2 Max 64gb RAM, 30B parameter.

This is the first run after downloading the repo, not likely cache issue.

![image](https://user-images.githubusercontent.com/6447905/227453036-d8f60d22-330a-4dc0-afa1-8452e6b93222.png)
