### ISSUE TITLE
Download 7B Got stuck

### ISSUE THREAD

**Issue by sshadmand** [nsarrazin/serge#111]
### Bug description

Thanks for creating this! Spinning up from Docker was super easy. HoweverMy "Download a model " of "7B" git stuck at 49.3%. Is there a way to see why it got stuck via the container? I have plenty of RAM, GPUs and Memory on my Mac OS M1. 

### Steps to reproduce

Ran 

` docker run -d -v weights:/usr/src/app/weights -v datadb:/data/db/  -p 8008:8008 ghcr.io/nsarrazin/serge:latest`
- open http://localhost:8008/models
- Go to downloads
- Select first download (7B)

### Environment Information

```
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.18.8
Built:        Wed Nov  9 12:43:58 2022
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      4.4.2
API Version:  4.4.2
Go Version:   go1.19.6
Built:        Wed Mar  1 03:22:39 2023
```

<img width="223" alt="Screenshot 2023-03-29 at 2 24 15 PM" src="https://user-images.githubusercontent.com/68735/228671122-25deb3b2-c35f-4fe2-8900-658c7c702ad0.png">

### Screenshots

<img width="759" alt="Screenshot 2023-03-29 at 2 04 20 PM" src="https://user-images.githubusercontent.com/68735/228670833-709586a1-9e95-4bdf-a260-ce6d44a5bdf5.png">

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by nsarrazin** [comment]
Can you refresh the page and check if it's still loading ?

**Comment by sshadmand** [comment]
@nsarrazin , thanks for the quick response. Yah - I tried refreshing the page a few times, but it seems cached. If there is a place where logs are stored in the container, I can check by going into interactive mode on the container and send that. Maybe that would help you, me, or others analyze. 

Until then, I will try to install 7B-native to see if that gets all the way done, and then restart the container worst case.

**Comment by sshadmand** [comment]
Update/FYI: just as I sent this I realized the 7B-native got stuck at 36%. 
<img width="915" alt="Screenshot 2023-03-29 at 2 43 41 PM" src="https://user-images.githubusercontent.com/68735/228674535-ed226f02-659d-4afe-94bd-f09f4e0be9a1.png">

**Comment by sshadmand** [comment]
For others with similar issues. Restarting container, starting over, and downloading 7B-native worked. 
<img width="329" alt="Screenshot 2023-03-29 at 3 37 31 PM" src="https://user-images.githubusercontent.com/68735/228683382-76848923-2c03-47e4-b46d-546cdb5806e2.png">
