### ISSUE TITLE
Cannot use the alpaca.7B model

### ISSUE THREAD

**Issue by VanHallein** [nsarrazin/serge#119]
### Bug description

I downloaded the ggml-alpaca-7b-q4.bin from the internet and docker cp it in to the /usr/src/app/weights folder. It is there now, however it stays unnoticed by Serge. Even after restarting and fumbling around, I cannot select the model when starting a chat. 

### Steps to reproduce

Download ggml-alpaca-7b-q4.bin
docker cp ./ggml-alpaca-7b-q4.bin <DOCKER CONTAINER>:/usr/src/app/weights
restarting the docker container

### Environment Information

Debian 10.03 runnig in VirtualBox
Docker version 23.0.2, build 569dd73

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by FenarkSEC** [comment]
Have you tried downloading 7B from the download manager included in Serge ?
Otherwise, you could try to rename your file from ggml-alpaca-7b-q4.bin to 7B.bin to see if Serge can detect it.

**Comment by gaby** [comment]
@VanHallein Did you figured out the issue?
