### ISSUE TITLE
API Server is hanging while converting model files

### ISSUE THREAD

**Issue by iSplasher** [nsarrazin/serge#12]
Tried setting it up exactly as README guides, but I keep getting this error, resulting in a 500 error:
![billede](https://user-images.githubusercontent.com/9113348/226945717-dae5fdb0-efd2-4b51-8173-a936113435b5.png)

**Comment by iSplasher** [comment]
Seems like a startup issue. I waited 10 mins before trying again, and now it works.

**Comment by nsarrazin** [comment]
I think I know what's happening here. 

When the server starts it converts the models if needed. This process happens on startup indeed and blocks the API server until it is complete. The API server is not up and so fetch is failing on the web.

I'll need to handle the error more gracefully in the front-end and find a way to run the conversion without blocking the API server.
