### ISSUE TITLE
30B model support

### ISSUE THREAD

**Issue by nsarrazin** [nsarrazin/serge#13]

**Comment by nsarrazin** [comment]
I've made the 30B model available to download but I don't have the hardware to test it. So if someone feels like it, feel free to download it ! Instructions are in the README.

**Comment by dacamp** [comment]
I can test it, but it looks like the 7B tokenizer is downloaded

![Screenshot 2023-03-22 at 11 36 08 AM](https://user-images.githubusercontent.com/2781009/227004451-4313d994-c320-4483-9c05-59d65ff6b4a9.png)

**Comment by dacamp** [comment]
I hacked it locally with this, but it's pretty jank. I think the model should determine the tokenizer.

```diff --git a/api/utils/download.py b/api/utils/download.py
index 73298b5..d0eafcb 100644
--- a/api/utils/download.py
+++ b/api/utils/download.py
@@ -10,6 +10,7 @@ models_info = {
     "13B": ["Pi3141/alpaca-13B-ggml", "ggml-model-q4_0.bin"],
     "30B": ["Pi3141/alpaca-30B-ggml", "ggml-model-q4_0.bin"],
     "tokenizer": ["decapoda-research/llama-7b-hf", "tokenizer.model"],
+    "30B-tokenizer": ["decapoda-research/llama-30b-hf", "tokenizer.model"],
 }


@@ -21,7 +22,7 @@ def parse_args():
         "model",
         help="Model name",
         nargs="+",
-        choices=["7B", "13B", "30B", "tokenizer"],
+        choices=["7B", "13B", "30B", "tokenizer", "30B-tokenizer"],
     )

     return parser.parse_args()
```

**Comment by nsarrazin** [comment]
> Hi guys, I just tested the 30B model, it works fine (with the conversion manually from https://gist.github.com/eiz/828bddec6162a023114ce19146cb2b82) and don't forget the modification in the llama cpp to load a single file for the 30b model.

Are you sure this is needed ? I was pretty sure the `--n_parts` argument to llama.cpp could let you handle it without modifying the source.

In serge it's handled there:
https://github.com/nsarrazin/serge/blob/58cf7d0f451035843d8b7e8cac048513fe47e01c/api/utils/generate.py#L47-L48

**Comment by nsarrazin** [comment]
I think you don't need to grab a different tokenizer, I believe they're exactly the same. 

You can check it here:
https://huggingface.co/decapoda-research/llama-30b-hf/blob/main/tokenizer.model
https://huggingface.co/decapoda-research/llama-13b-hf/blob/main/tokenizer.model
https://huggingface.co/decapoda-research/llama-7b-hf/blob/main/tokenizer.model

They all have the same SHA256 hash

**Comment by maximeseth** [comment]
Yes you right no need, i used same

**Comment by dacamp** [comment]
Thanks @maximeseth

**Comment by nsarrazin** [comment]
Seems like this could be closed then ?

**Comment by nsarrazin** [comment]
I'm closing this, I think it works. If it doesn't I'll reopen it.
