### ISSUE TITLE
Formatting is lost

### ISSUE THREAD

**Issue by johncadengo** [nsarrazin/serge#132]
### Bug description

I'm not sure if this formatting is being lost or if this is just the full response. But here's an example prompt that works in GPT4All that doesn't work in Serge.

The expected output would look something like this, just taken from the README on GPT4All:

> List 10 dogs.
> 
> 1. Labrador Retriever
> 2. Golden Retriever
> 3. Beagle
> 4. Poodle
> 5. German Shepherd
> 6. Bulldog
> 7. Rottweiler
> 8. Boxer
> 9. Shih Tzu
> 10. Pug

The actual output is something like this:

> Here are ten dogs listed numerically for your reference.

### Steps to reproduce

1. Enter in the prompt: "List 10 dogs."

### Environment Information

Docker version 20.10.17, build 100c701

### Screenshots

![Screenshot 2023-04-03 at 3 02 59 PM](https://user-images.githubusercontent.com/561587/229637227-ad1a74fe-14c9-44e9-92e8-5db541aef972.png)

### Relevant log output

``` INFO:     192.168.1.203:53956 - "GET /chat/bc25a0c6-1815-4735-b366-b412c202b4e1/question?prompt=List+10+dogs+in+a+numbered+format HTTP/1.1" 200 OK```

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gaby** [comment]
@johncadengo is this happening with the current latest tag?
