### ISSUE TITLE
Can't download model in K8s

### ISSUE THREAD

**Issue by solutioon** [nsarrazin/serge#137]
### Bug description

I try to run $ kubectl exec -it serge-58959fb6b7-px76v -n serge-ai python3 /usr/src/app/api/utils/download.py tokenizer 7B
 but I can't find that fie download.py in the container image.

### Steps to reproduce

kubectl exec -it serge-58959fb6b7-px76v -n serge-ai python3 /usr/src/app/api/utils/download.py

### Environment Information

K8s version: K3s
Version: Main

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by voarsh2** [comment]
Use "Download models" after running the docker image normally - in the web GUI......

**Comment by gaby** [comment]
@solutioon The download.py is deprecated, `serge` now includes a built-in download manager in the UI. 

Be sure to download the latest release: `ghcr.io/nsarrazin/serge:latest`

**Comment by solutioon** [comment]
Sorry, but doc in K8s is not updated. Trying to download, is there any way to check progress?
