### ISSUE TITLE
Docker exited code 132

### ISSUE THREAD

**Issue by zarigata** [nsarrazin/serge#146]
### Bug description

i have issue starting it, on docker command

### Steps to reproduce

install ubuntu server

-install git
-install docker
-run command
-proffit

### Environment Information

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="generator"  content="lshw-" />
<style type="text/css">
  .first {font-weight: bold; margin-left: none; padding-right: 1em;vertical-align: top; }
  .second {padding-left: 1em; width: 100%; vertical-align: center; }
  .id {font-family: monospace;}
  .indented {margin-left: 2em; border-left: dotted thin #dde; padding-bottom: 1em; }
  .node {border: solid thin #ffcc66; padding: 1em; background: #ffffcc; }
  .node-unclaimed {border: dotted thin #c3c3c3; padding: 1em; background: #fafafa; color: red; }
  .node-disabled {border: solid thin #f55; padding: 1em; background: #fee; color: gray; }
</style>
<title>chat-brl</title>
</head>
<body>
<div class="indented">
<table width="100%" class="node" summary="attributes of chat-brl">
 <thead><tr><td class="first">id:</td><td class="second"><div class="id">chat-brl</div></td></tr></thead>
 <tbody>
    <tr><td class="first">description: </td><td class="second">Desktop Computer</td></tr>
    <tr><td class="first">product: </td><td class="second">Virtual Machine (None)</td></tr>
    <tr><td class="first">vendor: </td><td class="second">Microsoft Corporation</td></tr>
    <tr><td class="first">version: </td><td class="second">Hyper-V UEFI Release v4.0</td></tr>
    <tr><td class="first">serial: </td><td class="second">0047-9490-4298-8277-3548-3835-18</td></tr>
    <tr><td class="first">width: </td><td class="second">64 bits</td></tr>
    <tr><td class="first">capabilities: </td><td class="second"><dfn title="SMBIOS version 3.1.1">smbios-3.1.1</dfn> <dfn title="DMI version 3.1.1">dmi-3.1.1</dfn> <dfn title="Symmetric Multi-Processing">smp</dfn> <dfn title="32-bit processes">vsyscall32</dfn> </td></tr>
    <tr><td class="first">configuration:</td><td class="second"><table summary="configuration of chat-brl"><tr><td class="sub-first"> boot</td><td>=</td><td>normal</td></tr><tr><td class="sub-first"> chassis</td><td>=</td><td>desktop</td></tr><tr><td class="sub-first"> family</td><td>=</td><td>Virtual Machine</td></tr><tr><td class="sub-first"> sku</td><td>=</td><td>None</td></tr><tr><td class="sub-first"> uuid</td><td>=</td><td>e95e9ebd-3b10-4c4e-b8ed-3f6280a4901d</td></tr></table></td></tr>
 </tbody></table></div>
<div class="indented">
        <div class="indented">
    <table width="100%" class="node" summary="attributes of core">
 <thead><tr><td class="first">id:</td><td class="second"><div class="id">core</div></td></tr></thead>
 <tbody>
       <tr><td class="first">description: </td><td class="second">Motherboard</td></tr>
       <tr><td class="first">product: </td><td class="second">Virtual Machine</td></tr>
       <tr><td class="first">vendor: </td><td class="second">Microsoft Corporation</td></tr>
       <tr><td class="first">physical id: </td><td class="second"><div class="id">0</div></td></tr>
       <tr><td class="first">version: </td><td class="second">Hyper-V UEFI Release v4.0</td></tr>
       <tr><td class="first">serial: </td><td class="second">0047-9490-4298-8277-3548-3835-18</td></tr>
       <tr><td class="first">slot: </td><td class="second">Virtual Machine</td></tr>
 </tbody>    </table></div>
<div class="indented">
              <div class="indented">
       <table width="100%" class="node" summary="attributes of firmware">
 <thead><tr><td class="first">id:</td><td class="second"><div class="id">firmware</div></td></tr></thead>
 <tbody>
          <tr><td class="first">description: </td><td class="second">BIOS</td></tr>
          <tr><td class="first">vendor: </td><td class="second">Microsoft Corporation</td></tr>
          <tr><td class="first">physical id: </td><td class="second"><div class="id">0</div></td></tr>
          <tr><td class="first">version: </td><td class="second">Hyper-V UEFI Release v4.0</td></tr>
          <tr><td class="first">date: </td><td class="second">03/13/2019</td></tr>
          <tr><td class="first">size: </td><td class="second">1MiB</td></tr>
          <tr><td class="first">capabilities: </td><td class="second"><dfn title="ACPI">acpi</dfn> <dfn title="UEFI specification is supported">uefi</dfn> <dfn title="This machine is a virtual machine">virtualmachine</dfn> </td></tr>
 </tbody>       </table></div>
       </div>
<div class="indented">
              <div class="indented">
       <table width="100%" class="node" summary="attributes of cpu:0">
 <thead><tr><td class="first">id:</td><td class="second"><div class="id">cpu:0</div></td></tr></thead>
 <tbody>
          <tr><td class="first">description: </td><td class="second">CPU</td></tr>
          <tr><td class="first">product: </td><td class="second">Intel(R) Xeon(R) CPU           L5640  @ 2.27GHz</td></tr>
          <tr><td class="first">vendor: </td><td class="second">Intel Corp.</td></tr>
          <tr><td class="first">physical id: </td><td class="second"><div class="id">4</div></td></tr>
          <tr><td class="first">bus info: </td><td class="second"><div class="id">cpu@0</div></td></tr>
          <tr><td class="first">version: </td><td class="second">6.44.2</td></tr>
          <tr><td class="first">serial: </td><td class="second">None</td></tr>
          <tr><td class="first">slot: </td><td class="second">None</td></tr>
          <tr><td class="first">size: </td><td class="second">2267MHz</td></tr>
          <tr><td class="first">width: </td><td class="second">64 bits</td></tr>
          <tr><td class="first">clock: </td><td class="second">133MHz</td></tr>
          <tr><td class="first">capabilities: </td><td class="second"><dfn title="64bits extensions (x86-64)">lm</dfn> <dfn title="mathematical co-processor">fpu</dfn> <dfn title="FPU exceptions reporting">fpu_exception</dfn> <dfn title="">wp</dfn> <dfn title="virtual mode extensions">vme</dfn> <dfn title="debugging extensions">de</dfn> <dfn title="page size extensions">pse</dfn> <dfn title="time stamp counter">tsc</dfn> <dfn title="model-specific registers">msr</dfn> <dfn title="4GB+ memory addressing (Physical Address Extension)">pae</dfn> <dfn title="machine check exceptions">mce</dfn> <dfn title="compare and exchange 8-byte">cx8</dfn> <dfn title="on-chip advanced programmable interrupt controller (APIC)">apic</dfn> <dfn title="fast system calls">sep</dfn> <dfn title="memory type range registers">mtrr</dfn> <dfn title="page global enable">pge</dfn> <dfn title="machine check architecture">mca</dfn> <dfn title="conditional move instruction">cmov</dfn> <dfn title="page attribute table">pat</dfn> <dfn title="36-bit page size extensions">pse36</dfn> <dfn title="">clflush</dfn> <dfn title="multimedia extensions (MMX)">mmx</dfn> <dfn title="fast floating point save/restore">fxsr</dfn> <dfn title="streaming SIMD extensions (SSE)">sse</dfn> <dfn title="streaming SIMD extensions (SSE2)">sse2</dfn> <dfn title="HyperThreading">ht</dfn> <dfn title="fast system calls">syscall</dfn> <dfn title="no-execute bit (NX)">nx</dfn> <dfn title="">pdpe1gb</dfn> <dfn title="">rdtscp</dfn> <dfn title="64bits extensions (x86-64)">x86-64</dfn> <dfn title="">constant_tsc</dfn> <dfn title="">rep_good</dfn> <dfn title="">nopl</dfn> <dfn title="">xtopology</dfn> <dfn title="">cpuid</dfn> <dfn title="">pni</dfn> <dfn title="">pclmulqdq</dfn> <dfn title="">ssse3</dfn> <dfn title="">cx16</dfn> <dfn title="">pcid</dfn> <dfn title="">sse4_1</dfn> <dfn title="">sse4_2</dfn> <dfn title="">popcnt</dfn> <dfn title="">aes</dfn> <dfn title="">hypervisor</dfn> <dfn title="">lahf_lm</dfn> <dfn title="">pti</dfn> <dfn title="">ibrs</dfn> <dfn title="">ibpb</dfn> <dfn title="">stibp</dfn> <dfn title="">arch_capabilities</dfn> </td></tr>
          <tr><td class="first">configuration:</td><td class="second"><table summary="configuration of cpu:0"><tr><td class="sub-first"> cores</td><td>=</td><td>8</td></tr><tr><td class="sub-first"> enabledcores</td><td>=</td><td>8</td></tr><tr><td class="sub-first"> microcode</td><td>=</td><td>4294967295</td></tr><tr><td class="sub-first"> threads</td><td>=</td><td>1</td></tr></table></td></tr>
 </tbody>       </table></div>
       </div>
<div class="indented">
              <div class="indented">
       <table width="100%" class="node" summary="attributes of cpu:1">
 <thead><tr><td class="first">id:</td><td class="second"><div class="id">cpu:1</div></td></tr></thead>
 <tbody>
          <tr><td class="first">description: </td><td class="second">CPU</td></tr>
          <tr><td class="first">product: </td><td class="second">Intel(R) Xeon(R) CPU           L5640  @ 2.27GHz</td></tr>
          <tr><td class="first">vendor: </td><td class="second">Intel Corp.</td></tr>
          <tr><td class="first">physical id: </td><td class="second"><div class="id">5</div></td></tr>
          <tr><td class="first">bus info: </td><td class="second"><div class="id">cpu@1</div></td></tr>
          <tr><td class="first">version: </td><td class="second">6.44.2</td></tr>
          <tr><td class="first">serial: </td><td class="second">None</td></tr>
          <tr><td class="first">slot: </td><td class="second">None</td></tr>
          <tr><td class="first">size: </td><td class="second">2267MHz</td></tr>
          <tr><td class="first">width: </td><td class="second">64 bits</td></tr>
          <tr><td class="first">clock: </td><td class="second">133MHz</td></tr>
          <tr><td class="first">capabilities: </td><td class="second"><dfn title="64bits extensions (x86-64)">lm</dfn> <dfn title="mathematical co-processor">fpu</dfn> <dfn title="FPU exceptions reporting">fpu_exception</dfn> <dfn title="">wp</dfn> <dfn title="virtual mode extensions">vme</dfn> <dfn title="debugging extensions">de</dfn> <dfn title="page size extensions">pse</dfn> <dfn title="time stamp counter">tsc</dfn> <dfn title="model-specific registers">msr</dfn> <dfn title="4GB+ memory addressing (Physical Address Extension)">pae</dfn> <dfn title="machine check exceptions">mce</dfn> <dfn title="compare and exchange 8-byte">cx8</dfn> <dfn title="on-chip advanced programmable interrupt controller (APIC)">apic</dfn> <dfn title="fast system calls">sep</dfn> <dfn title="memory type range registers">mtrr</dfn> <dfn title="page global enable">pge</dfn> <dfn title="machine check architecture">mca</dfn> <dfn title="conditional move instruction">cmov</dfn> <dfn title="page attribute table">pat</dfn> <dfn title="36-bit page size extensions">pse36</dfn> <dfn title="">clflush</dfn> <dfn title="multimedia extensions (MMX)">mmx</dfn> <dfn title="fast floating point save/restore">fxsr</dfn> <dfn title="streaming SIMD extensions (SSE)">sse</dfn> <dfn title="streaming SIMD extensions (SSE2)">sse2</dfn> <dfn title="HyperThreading">ht</dfn> <dfn title="fast system calls">syscall</dfn> <dfn title="no-execute bit (NX)">nx</dfn> <dfn title="">pdpe1gb</dfn> <dfn title="">rdtscp</dfn> <dfn title="64bits extensions (x86-64)">x86-64</dfn> <dfn title="">constant_tsc</dfn> <dfn title="">rep_good</dfn> <dfn title="">nopl</dfn> <dfn title="">xtopology</dfn> <dfn title="">cpuid</dfn> <dfn title="">pni</dfn> <dfn title="">pclmulqdq</dfn> <dfn title="">ssse3</dfn> <dfn title="">cx16</dfn> <dfn title="">pcid</dfn> <dfn title="">sse4_1</dfn> <dfn title="">sse4_2</dfn> <dfn title="">popcnt</dfn> <dfn title="">aes</dfn> <dfn title="">hypervisor</dfn> <dfn title="">lahf_lm</dfn> <dfn title="">pti</dfn> <dfn title="">ibrs</dfn> <dfn title="">ibpb</dfn> <dfn title="">stibp</dfn> <dfn title="">arch_capabilities</dfn> </td></tr>
          <tr><td class="first">configuration:</td><td class="second"><table summary="configuration of cpu:1"><tr><td class="sub-first"> cores</td><td>=</td><td>8</td></tr><tr><td class="sub-first"> enabledcores</td><td>=</td><td>4</td></tr><tr><td class="sub-first"> microcode</td><td>=</td><td>4294967295</td></tr><tr><td class="sub-first"> threads</td><td>=</td><td>1</td></tr></table></td></tr>
 </tbody>       </table></div>
       </div>
<div class="indented">
              <div class="indented">
       <table width="100%" class="node" summary="attributes of memory">
 <thead><tr><td class="first">id:</td><td class="second"><div class="id">memory</div></td></tr></thead>
 <tbody>
          <tr><td class="first">description: </td><td class="second">System Memory</td></tr>
          <tr><td class="first">physical id: </td><td class="second"><div class="id">7</div></td></tr>
          <tr><td class="first">slot: </td><td class="second">System board or motherboard</td></tr>
          <tr><td class="first">size: </td><td class="second">62GiB</td></tr>
 </tbody>       </table></div>
<div class="indented">
                    <div class="indented">
          <table width="100%" class="node" summary="attributes of bank:0">
 <thead><tr><td class="first">id:</td><td class="second"><div class="id">bank:0</div></td></tr></thead>
 <tbody>
             <tr><td class="first">product: </td><td class="second">None</td></tr>
             <tr><td class="first">vendor: </td><td class="second">Microsoft Corporation</td></tr>
             <tr><td class="first">physical id: </td><td class="second"><div class="id">0</div></td></tr>
             <tr><td class="first">serial: </td><td class="second">None</td></tr>
             <tr><td class="first">slot: </td><td class="second">M0001</td></tr>
             <tr><td class="first">size: </td><td class="second">3968MiB</td></tr>
 </tbody>          </table></div>
          </div>
<div class="indented">
                    <div class="indented">
          <table width="100%" class="node" summary="attributes of bank:1">
 <thead><tr><td class="first">id:</td><td class="second"><div class="id">bank:1</div></td></tr></thead>
 <tbody>
             <tr><td class="first">product: </td><td class="second">None</td></tr>
             <tr><td class="first">vendor: </td><td class="second">Microsoft Corporation</td></tr>
             <tr><td class="first">physical id: </td><td class="second"><div class="id">1</div></td></tr>
             <tr><td class="first">serial: </td><td class="second">None</td></tr>
             <tr><td class="first">slot: </td><td class="second">M0002</td></tr>
             <tr><td class="first">size: </td><td class="second">27GiB</td></tr>
 </tbody>          </table></div>
          </div>
<div class="indented">
                    <div class="indented">
          <table width="100%" class="node" summary="attributes of bank:2">
 <thead><tr><td class="first">id:</td><td class="second"><div class="id">bank:2</div></td></tr></thead>
 <tbody>
             <tr><td class="first">product: </td><td class="second">None</td></tr>
             <tr><td class="first">vendor: </td><td class="second">Microsoft Corporation</td></tr>
             <tr><td class="first">physical id: </td><td class="second"><div class="id">2</div></td></tr>
             <tr><td class="first">serial: </td><td class="second">None</td></tr>
             <tr><td class="first">slot: </td><td class="second">M0003</td></tr>
             <tr><td class="first">size: </td><td class="second">31GiB</td></tr>
 </tbody>          </table></div>
          </div>
       </div>
<div class="indented">
              <div class="indented">
       <table width="100%" class="node" summary="attributes of pnp00:00">
 <thead><tr><td class="first">id:</td><td class="second"><div class="id">pnp00:00</div></td></tr></thead>
 <tbody>
          <tr><td class="first">product: </td><td class="second">PnP device PNP0b00</td></tr>
          <tr><td class="first">physical id: </td><td class="second"><div class="id">1</div></td></tr>
          <tr><td class="first">capabilities: </td><td class="second"><dfn title="">pnp</dfn> </td></tr>
          <tr><td class="first">configuration:</td><td class="second"><table summary="configuration of pnp00:00"><tr><td class="sub-first"> driver</td><td>=</td><td>rtc_cmos</td></tr></table></td></tr>
 </tbody>       </table></div>
       </div>
<div class="indented">
              <div class="indented">
       <table width="100%" class="node" summary="attributes of scsi">
 <thead><tr><td class="first">id:</td><td class="second"><div class="id">scsi</div></td></tr></thead>
 <tbody>
          <tr><td class="first">physical id: </td><td class="second"><div class="id">2</div></td></tr>
          <tr><td class="first">logical name: </td><td class="second"><div class="id">scsi0</div></td></tr>
 </tbody>       </table></div>
<div class="indented">
                    <div class="indented">
          <table width="100%" class="node" summary="attributes of disk">
 <thead><tr><td class="first">id:</td><td class="second"><div class="id">disk</div></td></tr></thead>
 <tbody>
             <tr><td class="first">description: </td><td class="second">SCSI Disk</td></tr>
             <tr><td class="first">product: </td><td class="second">Virtual Disk</td></tr>
             <tr><td class="first">vendor: </td><td class="second">Msft</td></tr>
             <tr><td class="first">physical id: </td><td class="second"><div class="id">0.0.0</div></td></tr>
             <tr><td class="first">bus info: </td><td class="second"><div class="id">scsi@0:0.0.0</div></td></tr>
             <tr><td class="first">logical name: </td><td class="second"><div class="id">/dev/sda</div></td></tr>
             <tr><td class="first">version: </td><td class="second">1.0</td></tr>
             <tr><td class="first">size: </td><td class="second">127GiB (136GB)</td></tr>
             <tr><td class="first">capabilities: </td><td class="second"><dfn title="GUID Partition Table version 1.00">gpt-1.00</dfn> <dfn title="Partitioned disk">partitioned</dfn> <dfn title="GUID partition table">partitioned:gpt</dfn> </td></tr>
             <tr><td class="first">configuration:</td><td class="second"><table summary="configuration of disk"><tr><td class="sub-first"> ansiversion</td><td>=</td><td>5</td></tr><tr><td class="sub-first"> guid</td><td>=</td><td>684b0d08-619a-457c-b583-31bd22f07f6f</td></tr><tr><td class="sub-first"> logicalsectorsize</td><td>=</td><td>512</td></tr><tr><td class="sub-first"> sectorsize</td><td>=</td><td>4096</td></tr></table></td></tr>
 </tbody>          </table></div>
<div class="indented">
                          <div class="indented">
             <table width="100%" class="node-unclaimed" summary="attributes of volume:0">
 <thead><tr><td class="first">id:</td><td class="second"><div class="id">volume:0</div></td></tr></thead>
 <tbody>
                <tr><td class="first">description: </td><td class="second">Windows FAT volume</td></tr>
                <tr><td class="first">vendor: </td><td class="second">mkfs.fat</td></tr>
                <tr><td class="first">physical id: </td><td class="second"><div class="id">1</div></td></tr>
                <tr><td class="first">bus info: </td><td class="second"><div class="id">scsi@0:0.0.0,1</div></td></tr>
                <tr><td class="first">version: </td><td class="second">FAT32</td></tr>
                <tr><td class="first">serial: </td><td class="second">b652-6cd1</td></tr>
                <tr><td class="first">size: </td><td class="second">1073MiB</td></tr>
                <tr><td class="first">capacity: </td><td class="second">1074MiB</td></tr>
                <tr><td class="first">capabilities: </td><td class="second"><dfn title="Contains boot code">boot</dfn> <dfn title="Windows FAT">fat</dfn> <dfn title="initialized volume">initialized</dfn> </td></tr>
                <tr><td class="first">configuration:</td><td class="second"><table summary="configuration of volume:0"><tr><td class="sub-first"> FATs</td><td>=</td><td>2</td></tr><tr><td class="sub-first"> filesystem</td><td>=</td><td>fat</td></tr></table></td></tr>
 </tbody>             </table></div>
             </div>
<div class="indented">
                          <div class="indented">
             <table width="100%" class="node" summary="attributes of volume:1">
 <thead><tr><td class="first">id:</td><td class="second"><div class="id">volume:1</div></td></tr></thead>
 <tbody>
                <tr><td class="first">description: </td><td class="second">EXT4 volume</td></tr>
                <tr><td class="first">vendor: </td><td class="second">Linux</td></tr>
                <tr><td class="first">physical id: </td><td class="second"><div class="id">2</div></td></tr>
                <tr><td class="first">bus info: </td><td class="second"><div class="id">scsi@0:0.0.0,2</div></td></tr>
                <tr><td class="first">logical name: </td><td class="second"><div class="id">/dev/sda2</div></td></tr>
                <tr><td class="first">logical name: </td><td class="second"><div class="id">/boot</div></td></tr>
                <tr><td class="first">version: </td><td class="second">1.0</td></tr>
                <tr><td class="first">serial: </td><td class="second">df5e79e5-d73a-420e-b974-3ee4ad5700bc</td></tr>
                <tr><td class="first">size: </td><td class="second">2GiB</td></tr>
                <tr><td class="first">capabilities: </td><td class="second"><dfn title="">journaled</dfn> <dfn title="Extended Attributes">extended_attributes</dfn> <dfn title="4GB+ files">large_files</dfn> <dfn title="16TB+ files">huge_files</dfn> <dfn title="directories with 65000+ subdirs">dir_nlink</dfn> <dfn title="needs recovery">recover</dfn> <dfn title="64bit filesystem">64bit</dfn> <dfn title="extent-based allocation">extents</dfn> <dfn title="">ext4</dfn> <dfn title="EXT2/EXT3">ext2</dfn> <dfn title="initialized volume">initialized</dfn> </td></tr>
                <tr><td class="first">configuration:</td><td class="second"><table summary="configuration of volume:1"><tr><td class="sub-first"> created</td><td>=</td><td>2023-04-08 14:34:15</td></tr><tr><td class="sub-first"> filesystem</td><td>=</td><td>ext4</td></tr><tr><td class="sub-first"> lastmountpoint</td><td>=</td><td>/boot</td></tr><tr><td class="sub-first"> modified</td><td>=</td><td>2023-04-08 14:54:41</td></tr><tr><td class="sub-first"> mount.fstype</td><td>=</td><td>ext4</td></tr><tr><td class="sub-first"> mount.options</td><td>=</td><td>rw,relatime</td></tr><tr><td class="sub-first"> mounted</td><td>=</td><td>2023-04-08 14:54:41</td></tr><tr><td class="sub-first"> state</td><td>=</td><td>mounted</td></tr></table></td></tr>
 </tbody>             </table></div>
             </div>
<div class="indented">
                          <div class="indented">
             <table width="100%" class="node" summary="attributes of volume:2">
 <thead><tr><td class="first">id:</td><td class="second"><div class="id">volume:2</div></td></tr></thead>
 <tbody>
                <tr><td class="first">description: </td><td class="second">EFI partition</td></tr>
                <tr><td class="first">physical id: </td><td class="second"><div class="id">3</div></td></tr>
                <tr><td class="first">bus info: </td><td class="second"><div class="id">scsi@0:0.0.0,3</div></td></tr>
                <tr><td class="first">logical name: </td><td class="second"><div class="id">/dev/sda3</div></td></tr>
                <tr><td class="first">serial: </td><td class="second">BhTm8M-I9dL-vGEP-GDrL-Ai0Y-sPPK-1pJKN4</td></tr>
                <tr><td class="first">size: </td><td class="second">123GiB</td></tr>
                <tr><td class="first">capabilities: </td><td class="second"><dfn title="">lvm2</dfn> </td></tr>
 </tbody>             </table></div>
             </div>
          </div>
<div class="indented">
                    <div class="indented">
          <table width="100%" class="node" summary="attributes of cdrom">
 <thead><tr><td class="first">id:</td><td class="second"><div class="id">cdrom</div></td></tr></thead>
 <tbody>
             <tr><td class="first">description: </td><td class="second">SCSI CD-ROM</td></tr>
             <tr><td class="first">product: </td><td class="second">Virtual DVD-ROM</td></tr>
             <tr><td class="first">vendor: </td><td class="second">Msft</td></tr>
             <tr><td class="first">physical id: </td><td class="second"><div class="id">0.0.1</div></td></tr>
             <tr><td class="first">bus info: </td><td class="second"><div class="id">scsi@0:0.0.1</div></td></tr>
             <tr><td class="first">logical name: </td><td class="second"><div class="id">/dev/cdrom</div></td></tr>
             <tr><td class="first">logical name: </td><td class="second"><div class="id">/dev/sr0</div></td></tr>
             <tr><td class="first">version: </td><td class="second">1.0</td></tr>
             <tr><td class="first">capabilities: </td><td class="second"><dfn title="support is removable">removable</dfn> <dfn title="Audio CD playback">audio</dfn> </td></tr>
             <tr><td class="first">configuration:</td><td class="second"><table summary="configuration of cdrom"><tr><td class="sub-first"> status</td><td>=</td><td>ready</td></tr></table></td></tr>
 </tbody>          </table></div>
<div class="indented">
                          <div class="indented">
             <table width="100%" class="node" summary="attributes of medium">
 <thead><tr><td class="first">id:</td><td class="second"><div class="id">medium</div></td></tr></thead>
 <tbody>
                <tr><td class="first">physical id: </td><td class="second"><div class="id">0</div></td></tr>
                <tr><td class="first">logical name: </td><td class="second"><div class="id">/dev/cdrom</div></td></tr>
 </tbody>             </table></div>
             </div>
          </div>
       </div>
    </div>
<div class="indented">
        <div class="indented">
    <table width="100%" class="node" summary="attributes of graphics">
 <thead><tr><td class="first">id:</td><td class="second"><div class="id">graphics</div></td></tr></thead>
 <tbody>
       <tr><td class="first">product: </td><td class="second">hyperv_drmdrmfb</td></tr>
       <tr><td class="first">physical id: </td><td class="second"><div class="id">1</div></td></tr>
       <tr><td class="first">logical name: </td><td class="second"><div class="id">/dev/fb0</div></td></tr>
       <tr><td class="first">capabilities: </td><td class="second"><dfn title="framebuffer">fb</dfn> </td></tr>
       <tr><td class="first">configuration:</td><td class="second"><table summary="configuration of graphics"><tr><td class="sub-first"> depth</td><td>=</td><td>32</td></tr><tr><td class="sub-first"> resolution</td><td>=</td><td>1024,768</td></tr></table></td></tr>
 </tbody>    </table></div>
    </div>
<div class="indented">
        <div class="indented">
    <table width="100%" class="node" summary="attributes of input:0">
 <thead><tr><td class="first">id:</td><td class="second"><div class="id">input:0</div></td></tr></thead>
 <tbody>
       <tr><td class="first">product: </td><td class="second">AT Translated Set 2 keyboard</td></tr>
       <tr><td class="first">physical id: </td><td class="second"><div class="id">2</div></td></tr>
       <tr><td class="first">logical name: </td><td class="second"><div class="id">input0</div></td></tr>
       <tr><td class="first">logical name: </td><td class="second"><div class="id">/dev/input/event0</div></td></tr>
       <tr><td class="first">capabilities: </td><td class="second"><dfn title="i8042 PC AT keyboard controller">i8042</dfn> </td></tr>
 </tbody>    </table></div>
    </div>
<div class="indented">
        <div class="indented">
    <table width="100%" class="node" summary="attributes of input:1">
 <thead><tr><td class="first">id:</td><td class="second"><div class="id">input:1</div></td></tr></thead>
 <tbody>
       <tr><td class="first">product: </td><td class="second">Microsoft Vmbus HID-compliant Mouse</td></tr>
       <tr><td class="first">physical id: </td><td class="second"><div class="id">3</div></td></tr>
       <tr><td class="first">logical name: </td><td class="second"><div class="id">input1</div></td></tr>
       <tr><td class="first">logical name: </td><td class="second"><div class="id">/dev/input/event1</div></td></tr>
       <tr><td class="first">logical name: </td><td class="second"><div class="id">/dev/input/js0</div></td></tr>
       <tr><td class="first">logical name: </td><td class="second"><div class="id">/dev/input/mouse0</div></td></tr>
       <tr><td class="first">capabilities: </td><td class="second"><dfn title="">virtual</dfn> </td></tr>
 </tbody>    </table></div>
    </div>
<div class="indented">
        <div class="indented">
    <table width="100%" class="node" summary="attributes of network">
 <thead><tr><td class="first">id:</td><td class="second"><div class="id">network</div></td></tr></thead>
 <tbody>
       <tr><td class="first">description: </td><td class="second">Ethernet interface</td></tr>
       <tr><td class="first">physical id: </td><td class="second"><div class="id">4</div></td></tr>
       <tr><td class="first">logical name: </td><td class="second"><div class="id">eth0</div></td></tr>
       <tr><td class="first">serial: </td><td class="second">00:15:5d:0f:03:01</td></tr>
       <tr><td class="first">size: </td><td class="second">100Mbit/s</td></tr>
       <tr><td class="first">capabilities: </td><td class="second"><dfn title="">ethernet</dfn> <dfn title="Physical interface">physical</dfn> </td></tr>
       <tr><td class="first">configuration:</td><td class="second"><table summary="configuration of network"><tr><td class="sub-first"> autonegotiation</td><td>=</td><td>off</td></tr><tr><td class="sub-first"> broadcast</td><td>=</td><td>yes</td></tr><tr><td class="sub-first"> driver</td><td>=</td><td>hv_netvsc</td></tr><tr><td class="sub-first"> driverversion</td><td>=</td><td>5.19.0-32-generic</td></tr><tr><td class="sub-first"> duplex</td><td>=</td><td>full</td></tr><tr><td class="sub-first"> firmware</td><td>=</td><td>N/A</td></tr><tr><td class="sub-first"> ip</td><td>=</td><td>192.168.15.18</td></tr><tr><td class="sub-first"> link</td><td>=</td><td>yes</td></tr><tr><td class="sub-first"> multicast</td><td>=</td><td>yes</td></tr><tr><td class="sub-first"> speed</td><td>=</td><td>100Mbit/s</td></tr></table></td></tr>
 </tbody>    </table></div>
    </div>
</body>
</html>

### Relevant log output

```shell
I llama.cpp build info:
I UNAME_S:  Linux
I UNAME_P:  x86_64
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -Wno-unused-function -pthread -march=native -mtune=native
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -pthread -march=native -mtune=native
I LDFLAGS:
I CC:       cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
I CXX:      g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

cc  -I.              -O3 -DNDEBUG -std=c11   -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -Wno-unused-function -pthread -march=native -mtune=native   -c ggml.c -o ggml.o
ggml.c: In function 'quantize_row_q4_0':
ggml.c:558:15: warning: unused variable 'nb' [-Wunused-variable]
  558 |     const int nb = k / QK;
      |               ^~
ggml.c: In function 'quantize_row_q4_1':
ggml.c:856:27: warning: unused variable 'y' [-Wunused-variable]
  856 |     block_q4_1 * restrict y = vy;
      |                           ^
ggml.c:854:15: warning: unused variable 'nb' [-Wunused-variable]
  854 |     const int nb = k / QK;
      |               ^~
g++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -pthread -march=native -mtune=native -c llama.cpp -o llama.o
g++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -pthread -march=native -mtune=native -c examples/common.cpp -o common.o
g++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -pthread -march=native -mtune=native examples/main/main.cpp ggml.o llama.o common.o -o main

====  Run ./main -h for help.  ====

g++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -pthread -march=native -mtune=native examples/quantize/quantize.cpp ggml.o llama.o -o quantize
g++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -pthread -march=native -mtune=native examples/perplexity/perplexity.cpp ggml.o llama.o common.o -o perplexity
g++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -pthread -march=native -mtune=native examples/embedding/embedding.cpp ggml.o llama.o common.o -o embedding
./deploy.sh: line 10:    54 Illegal instruction     (core dumped) mongod
```

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gaby** [comment]
MongoDB is crashing, which means your CPU doesnt support AVX / AVX2. Which CPU are you using?

**Comment by gaby** [comment]
Yeah, your intel cpu can't run llama.cpp, and can't run modern MongoDB 5.x / 6.x
