### ISSUE TITLE
CI/CD Docker pipeline

### ISSUE THREAD

**Issue by robotdjman** [nsarrazin/serge#15]
Love the project and I would love to contribute! My first thought its building a quick CI/CD pipeline with GitHub actions that allows any merge into a "release" branch would trigger a build of a docker image and upload it to the GitHub package repo. This way people can use their own docker-compose.yml (or the provided one in the repo) and pull the images without building them. Would I be able to get this setup?

Edit: Grammar

**Comment by nsarrazin** [comment]
I think this would be super nice to have. We would need a better way to handle downloading models then, but I love the idea.

Would there also be a way to wrap everything together into one image, API Server, DB & frontend ? Might be impossible, idk.

**Comment by rursache** [comment]
> @nsarrazin Would there also be a way to wrap everything together into one image, API Server, DB & fronted ?

I would also like this

**Comment by robotdjman** [comment]
@nsarrazin Yeah we could combine them into one image, but we could also do multiple images if they can be used on their own so people could have different setups. You can have multiple docker packages per GitHub repo.

**Comment by robotdjman** [comment]
@nsarrazin Got those actions created, could I be added as a contributor to submit a pull request? 😃

**Comment by robotdjman** [comment]
> 
Not yet but working on that now, I'll submit a new request with those changes later today with docker images that are fully self contained (but still separate images api/webui)
