### ISSUE TITLE
How to use the api

### ISSUE THREAD

**Issue by MisterE123** [nsarrazin/serge#155]
### Bug description

The documentation does not describe how to use the API.

I would expect instructions for setting up a python environment using windows or linux

### Steps to reproduce

...

### Environment Information

Windows 11, docker on WSL

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by DVSProductions** [comment]
Serge just uses a REST api. There is nothing to document besides the API. Here are the API docs: http://localhost:8008/api/docs you can find the openapi definition under http://localhost:8008/api/openapi.json
If you need help setting up a python environment, just google REST api python. 
This sort of information is readily available in other places.

**Comment by frozenfoxx** [comment]
A link to the `/api/docs` on the `README.md` would have been pretty helpful, I know I was looking for the same information.

**Comment by gaby** [comment]
@frozenfoxx I will update the readme, thanks!
