### ISSUE TITLE
Spelling of LLaMA

### ISSUE THREAD

**Issue by mcmonkey4eva** [nsarrazin/serge#156]
It's weird how many times I've had to [submit an issue like this](https://github.com/qwopqwop200/GPTQ-for-LLaMa/issues/92) but - it's spelled `LLaMA`, capital `A` on the end, not `LLaMa`.
You can verify this via their official Paper https://arxiv.org/abs/2302.13971

**Comment by gaby** [comment]
@mcmonkey4eva I will fix this one in a bit. Thanks for reporting!
