### ISSUE TITLE
Experimented with a version that doesn't require AVX

### ISSUE THREAD

**Issue by telnetdoogie** [nsarrazin/serge#159]
I don't know how useful this would be for anyone, but I forked this repo and worked on getting a build working with mongo 4.4 to remove the hard AVX requirement... it "works" but obviously without AVX hardware it's very slow (depending on your CPU obviously) 

I was motivated to see if I could get it working for folks on Synology units with non AVX CPUs which is why I decided to give it a whirl. There's really nothing different about the build other than it uses the older version of mongo. None of the actual serge code is changed whatsoever.

I _could_ PR this back to this repo if there's interest in folding it back in somehow, but obviously because it's a different dockerfile and docker image, and uses an older version of mongo, it'd have to be a long-lived separate branch versus a contribution to the main branch. Also, it could be kind of a pain to maintain as the main branch continues to grow. I could just also keep it as a fork, but based on how it performs for my own device I doubt my motivation to maintain it will be very high at all.

If anyone wants to give running it a try just for giggles, the fork is at [https://github.com/telnetdoogie/serge-noavx](https://github.com/telnetdoogie/serge-noavx) 

and you can pull the latest version to test drive it with 
 ```bash
docker pull ghcr.io/telnetdoogie/serge-noavx:latest
 ```
 I ran it on a NAS with a dual-core Intel Celeron J3355 and it works, but it took about 18 minutes to tell me who the President of France is :)

**Comment by snxraven** [comment]
AVX1 is actually supported in llama.cpp within recent merges see: https://github.com/ggerganov/llama.cpp/commit/02c5b27e91a6d18cf1043d3a2d8dbc59610ac257

From what I understand, Mongo will no longer be required within the next backend version.

Please see: https://github.com/nsarrazin/serge/pull/148

The maintainer can chime in more here as well :)

**Comment by telnetdoogie** [comment]
That's cool! FYI the Celeron, as an example (what my NAS is running with) doesn't support AVX1, not just an AVX2 issue :)

Removal of Mongo would remove the blocker for installation though on these devices. There doesn't seem to be a problem running serge without AVX right now on this device, but that might not be true in the future.

**Comment by snxraven** [comment]
If it works it works :) Hopefully the slowness can be worked out in llama.cpp someday. 

Celeron is a good point!

**Comment by telnetdoogie** [comment]
The reference to #148 is super helpful though.. that means my question about a potential PR and maintenance etc. is answered and nullified... no need for any of that soon, it looks like! Thanks so much @snxraven 

Hopefully the fork referenced above might tide any folks over if they've been wanting to try using this on some non-conforming hardware in the meantime.

**Comment by gaby** [comment]
@telnetdoogie PR #143 will get rid of MongoDB making it easier to run in more CPU's even if it's slow.

I'm working on adding support so that people can test PR's using Docker.

**Comment by nsarrazin** [comment]
@telnetdoogie We recently merged a PR that gets rid of mongodb, so there should be no AVX requirements anymore. Let me know if that also works with your celeron !

**Comment by telnetdoogie** [comment]
@nsarrazin works !! thanks much! Love it!
