### ISSUE TITLE
Demo video not accessible via github or serge website

### ISSUE THREAD

**Issue by nodecentral** [nsarrazin/serge#199]
### Bug description

Sorry, not really a bug, but I’d love to see some examples of this tool being used, and the video posted is not working.

### Steps to reproduce

Click on the video link in the repository readme page

### Environment Information

N/a

### Screenshots

![4A453080-B886-4E2E-AE2B-147BD07586B3](https://user-images.githubusercontent.com/4349292/233026218-f48fbfc6-4bdb-44a2-b67b-fba5fe666fe3.png)

### Relevant log output

```shell
N/a
```

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gaby** [comment]
@nodecentral The video works fine for me, something must be blocking it on your end?

**Comment by nodecentral** [comment]
I’m accessing it via Safari on an iPad, it’s all I currently have access to, could that be it ? Is the video encoded in a format iOS can play ?

**Comment by gaby** [comment]
@nodecentral It is a .webm file hosted at GitHub. Download chrome/firefox and visit the page on your iPad :-)

https://user-images.githubusercontent.com/25119303/226897188-914a6662-8c26-472c-96bd-f51fc020abf6.webm

**Comment by nodecentral** [comment]
Hi @gaby , sorry for the later reply, unfortunately it does the same thing when i use chrome (on the iPad).

I believe all apps on ios use the same apple web elements, as I’ve tried a few bespoke browser apps too, and all give me the same result.

https://github.com/nsarrazin/serge
