### ISSUE TITLE
Option for pre-loading specific models into memory

### ISSUE THREAD

**Issue by toasterrepairman** [nsarrazin/serge#21]
Not sure if this feature is possible, but I'd like the ability to specify (preferably in my .env file) models to leave pre-loaded in memory. It shouldn't be the default choice, but it would allow bandwidth-constrained servers to run faster, as well as reducing overall latency when running as an API.

Thanks for making this, and I look forward to seeing your plans for the API refactor! :smiley:

**Comment by thomasleveil** [comment]
Here are some thoughts : 
- [tweet from Justine tunney about loading model with mmap](https://twitter.com/justinetunney/status/1636628000493174784)
- [using mmap in python](https://realpython.com/python-mmap/#reading-a-memory-mapped-file-with-pythons-mmap)

But maybe a simpler way would be to declare a path as a `tmpfs` in the docker-compose file, and have the api code copy the files into that tmpfs location at startup.

I'm curious what other ideas people will come with on that matter

**Comment by maximeseth** [comment]
Hi, on my side I already tested by mounting in tmpfs the /var/lib/docker directory and the repository directory (manually via the unix system), and it's hardly faster if you already have an nvme, in any case I didn't notice much difference.

**Comment by maximeseth** [comment]
On the other hand I wonder if increasing the priority of the processes at startup when it generates a conversation would be interesting ex: "chrt -f 90 llama".
And above all, wouldn't it be more efficient to run the process directly outside of docker.

**Comment by maximeseth** [comment]
Just clone and build branch with mmap allocation, and yes is faster than main branch, is like instant when process is running.
https://github.com/ggerganov/llama.cpp/tree/mmap
I try some modification for allocation on memory in main.cpp.

**Comment by maximeseth** [comment]
![Main branch version](https://user-images.githubusercontent.com/107115334/227200578-d42e4f72-20ad-4724-a70c-b4fa324cef7e.png)

**Comment by maximeseth** [comment]
Here is main version : 

![image](https://user-images.githubusercontent.com/107115334/227205673-431e3cc3-aa44-4501-8333-582f763c6449.png)

**Comment by maximeseth** [comment]
And version custom with mmap allocation (i added some code to enable back avx512 on this version).

![image](https://user-images.githubusercontent.com/107115334/227205836-8c4cfd74-7621-43d8-ba61-bbb75075b635.png)

**Comment by gaby** [comment]
Closed via #129
