### ISSUE TITLE
Error: 'utf-8' codec can't decode byte 0xf0 in position 0: unexpected end of data

### ISSUE THREAD

**Issue by SimplexShotz** [nsarrazin/serge#218]
### Bug description

When using the chatbot, it will sometimes generate the entire message, but then throw the error:
`'utf-8' codec can't decode byte 0xf0 in position 0: unexpected end of data`
...once the message is done being generated.

This has happened with the 30B and the 13B models, and I would assume that it can also happen with the others.

### Steps to reproduce

1. Send a message to the chatbot
2. The error may or may not occur (I haven't found any reason in particular why the error occurs)

### Environment Information

Docker Version: 20.10.24, build 297e128
OS: Windows 10 Home 21H2 (19044.2846)
CPU Model: Ryzen 9 5900x
GPU Model: RTX 3080 FE
Browser: Chrome, Version 112.0.5615.138 (Official Build) (64-bit)

### Screenshots

![image](https://user-images.githubusercontent.com/44213379/234097777-9a97e259-c54c-4df4-93a1-ca20d144b706.png)

### Relevant log output

The docker container prints the following output (timestamps removed):
`ERROR    | serge.routers.chat:event_generator:189 - 'utf-8' codec can't decode byte 0xf0 in position 0: unexpected end of data`
`ERROR 'utf-8' codec can't decode byte 0xf0 in position 0: unexpected end of data`

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by nsarrazin** [comment]
I think it should be fixed with the latest version of main, please let me know!

**Comment by gaby** [comment]
@SimplexShotz Can you check if it still happens with latest tag?
