### ISSUE TITLE
Support: port 8008 port being used? But it's not..

### ISSUE THREAD

**Issue by hkirsman** [nsarrazin/serge#222]
Tried to run the command in readme and it pulls everything, then says can't run as the port is being used.

I tried with netstat -ano and I don't see port 8008 port being used. I think that would not make sense either - it seems pretty unique.

Anything else I could try?

**Comment by FeZzko** [comment]
Hi, I just had the problem, you can replace 8008:8008 with 8009:8008.

**Comment by hkirsman** [comment]
It worked, thanks!
