### ISSUE TITLE
Any ways it will work an a raspberry pi?

### ISSUE THREAD

**Issue by seyo-IV** [nsarrazin/serge#31]
I get this error
MongoDB requires ARMv8.2-A

I'm running it on a raspberry pi 4. Everything works accept the mongo db which exites as soon as I start it

**Comment by toasterrepairman** [comment]
I think it should, at least on the latest version. Try pulling the latest version of the repo and see if it helps, it should have a cross-platform Mongo container now. If that doesn't work, you can also try editing docker-compose.yml to load a compatible image.

**Comment by nsarrazin** [comment]
Can you try this branch https://github.com/nsarrazin/serge/pull/34 @seyo-IV  ? I fixed all the versions, it should work

**Comment by seyo-IV** [comment]
It worked with the 4.4.18
