### ISSUE TITLE
Blocks of code lose formatting

### ISSUE THREAD

**Issue by greenfoo** [nsarrazin/serge#325]
### Bug description

When the answer provided by the AI includes a block of code, the format is lost:
* Font is not monospace
* Leading spaces (indentation) is lost

Example:
![image](https://github.com/nsarrazin/serge/assets/42691086/10ae4a79-99ae-4994-a527-c32ec41cf395)

In the terminal/logs the response contains the expected indentation:
![image](https://github.com/nsarrazin/serge/assets/42691086/b6549971-521c-4a0b-9089-20be8adfca6f)

### Steps to reproduce

Ask the AI to print a piece of code.

### Environment Information

Docker image:
```ghcr.io/nsarrazin/serge:latest (d4ff2887270f) from May 22nd``` 

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gaby** [comment]
This is fixed by #210
