### ISSUE TITLE
Guanaco model not listed in download model section

### ISSUE THREAD

**Issue by ColinRoye** [nsarrazin/serge#343]
### Bug description

Expected: Guanaco models can be downloaded from "Download Models" section

Actual: Not Listed

### Steps to reproduce

1. go to Download a model
2. model dne

### Environment Information

Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1

### Screenshots

![image](https://github.com/nsarrazin/serge/assets/25215593/dbf02c2b-470e-4dc8-9c95-ce92fde9c01b)

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gaby** [comment]
@ColinRoye I need to update the README. The new models are only available in the "main" tag. The "latest" tag still points to v0.1.3 which uses ggmlv2
