### ISSUE TITLE
 Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json

### ISSUE THREAD

**Issue by Donavan** [nsarrazin/serge#35]
While trying to figure out why prompts were hanging I check the logs and found this:

6-be6b-40cb-95cb-69c96b0f9d05" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0" "-"
web_1      |
web_1      | > web@0.0.1 dev
web_1      | > vite dev --host 0.0.0.0 --port 9123
web_1      |
web_1      | ▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]
web_1      |
web_1      |     tsconfig.json:2:12:
web_1      |       2 │   "extends": "./.svelte-kit/tsconfig.json",
web_1      |         ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
web_1      |
web_1      |
web_1      | Forced re-optimization of dependencies
web_1      |
web_1      |   VITE v4.2.0  ready in 1285 ms
web_1      |
web_1      |   ➜  Local:   http://localhost:9123/
web_1      |   ➜  Network: http://172.19.0.4:9123/
web_1      | 5:37:04 PM [vite-plugin-svelte] ssr compile in progress ...
web_1      |

**Comment by gaby** [comment]
Compiling the image is no longer required. Give this a try:

```
docker run -d \
         -v weights:/usr/src/app/weights -v datadb:/data/db/ \
         -p 8008:8008 ghcr.io/nsarrazin/serge:latest
```

Then visit http://localhost:8008
