### ISSUE TITLE
Instructions for setting up development environment

### ISSUE THREAD

**Issue by security-companion** [nsarrazin/serge#354]
### Bug description

Hi,
I tried to set up the development environment as described in the Readme.
First I entered the following 2 commands:
`git clone https://github.com/nsarrazin/serge.git
DOCKER_BUILDKIT=1 docker compose -f docker-compose.dev.yml up -d --build`

Everything installed fine but in the docker logs I found the following:
`▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]

    tsconfig.json:2:12:
      2 │   "extends": "./.svelte-kit/tsconfig.json",
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

I found issue #35 with the same problem.
Suggestion for solving was to not run any more above command but instead docker run

So my question is: What is the current setup for development? Eg. if I want to adapt the web-GUI code and then see changes right away in my browser.

### Steps to reproduce

see above

### Environment Information

Windows 10

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gaby** [comment]
@security-companion Hello! It's just a warning from tscript. If you only want to run Serge do Docker run. If you plan on modifying the code or submitting a PR then follow the dev instructions.

**Comment by gaby** [comment]
Also join the Discord, plenty of people can help there :-)
