### ISSUE TITLE
Using pre-existing weights does not load into the interface

### ISSUE THREAD

**Issue by eshahrabani** [nsarrazin/serge#36]
Using ggml-alpaca-30b-q4.bin in the api/weights folder and rebuilding the entire app, it still does not appear as a model that can be selected in the settings.

**Comment by nsarrazin** [comment]
Hey ! So if you pull the latest main you can put your weights manually with `docker cp`

Something like `docker cp path/to/local/model.bin docker_id:/usr/src/app/weights` 

get the docker_id with `docker ps` 

And with the latest main it should be persisted to a volume.
