### ISSUE TITLE
Questions about the copyright

### ISSUE THREAD

**Issue by ThatCoffeeGuy** [nsarrazin/serge#45]
Hello,

First of all, thank you for making this! I have a question about the copyright part of the project though. If I understand this correctly, Meta only released such models for Academic students, but these are converted ones.

1.) As an academic student, can I use these freely? Is it safe and legal to upload, modify, finetune these models?
2.) If I'm not an academic student, can I still use these? 

Thank you!

**Comment by mzeng1417** [comment]
I believe the models are available for research/noncommerical use, not just "for students".

You may find out more from their website (stanford alpaca)
https://crfm.stanford.edu/2023/03/13/alpaca.html

**Comment by MohamedElashri** [comment]
I think down the road there is a problem with that. Meta license does not allow the usage as we think. It is available for research purposes, but with their permission. The available models circulated on the internet are leaked. And they seem to start to [crack down](https://github.com/github/dmca/blob/master/2023/03/2023-03-21-meta.md) the repositories that contain download info
