### ISSUE TITLE
VITE is not insalled in the docker image

### ISSUE THREAD

**Issue by nitnelave** [nsarrazin/serge#50]
Since we're mounting the node_modules, it works if the host has VITE installed. But in a more isolated scenario where the node_modules are in a volume or just part of the image, VITE should already be installed in the image.

Context: I don't use npm at all (don't have it installed) and so running the container didn't work (VITE not found). Worked after I logged into the container and `npm install vite`

**Comment by gaby** [comment]
Compiling is no longer required, you can use the official image now, give this a try:

```
docker run -d \
         -v weights:/usr/src/app/weights -v datadb:/data/db/ \
         -p 8008:8008 ghcr.io/nsarrazin/serge:latest
```

Then visit http://localhost:8008
