### ISSUE TITLE
i cant get it in install on windows 11 

### ISSUE THREAD

**Issue by DMTarmey** [nsarrazin/serge#52]
C:\Windows\System32>pip install serge
ERROR: Could not find a version that satisfies the requirement serge (from versions: none)
ERROR: No matching distribution found for serge

C:\Windows\System32>git clone https://github.com/nsarrazin/serge.git && cd serge
Cloning into 'serge'...
remote: Enumerating objects: 434, done.
remote: Counting objects: 100% (109/109), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 434 (delta 80), reused 74 (delta 70), pack-reused 325
Receiving objects: 100% (434/434), 95.56 KiB | 1.99 MiB/s, done.
Resolving deltas: 100% (247/247), done.

C:\Windows\System32\serge>
C:\Windows\System32\serge>cp .env.sample .env
'cp' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32\serge>
C:\Windows\System32\serge>docker compose up -d
'docker' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32\serge>docker compose exec api python3 /usr/src/app/utils/download.py tokenizer 7B
'docker' is not recognized as an internal or external command,
operable program or batch file.

**Comment by willjasen** [comment]
Assuming you have docker-compose on your system, change the last two commands to be docker-compose (no space)

**Comment by nsarrazin** [comment]
replace `cp` by `copy` for windows on the second command.

You will also need to install docker desktop for windows, probably WSL2 too. It's outside the scope of this repo (I'll update the readme though) but if you can get `docker compose version` running I'll gladly help you with the rest!

**Comment by willjasen** [comment]
> Please don't try to use `docker-compose` here! Don't think it will work.

Interesting.. will keep this in mind! Though I had to use the hyphen during my attempted deployments so far, the space didn't work.

**Comment by Ondry4K** [comment]
`copy .env.sample .env`
Gets me: 
`The system cannot find the file specified.`
I cant find the env sample anywhere idk if im just dumb or..
