### ISSUE TITLE
exit code 100

### ISSUE THREAD

**Issue by Hant7** [nsarrazin/serge#67]
### Bug description

failed to solve: executor failed running [/bin/sh -c apt-get install -y python3-pip]: exit code: 100

execute command "docker compose up -d"

### Steps to reproduce

install docker
install dependences
execute the commands for the instructions

### Environment Information

Docker version 20.10.17, build 100c70180f

### Screenshots

![image](https://user-images.githubusercontent.com/125782111/227747444-869aea45-daa3-46dd-ae3a-96a8a3191a2b.png)

### Relevant log output

```shell
Ubuntu
```

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gaby** [comment]
@Hant7 Is still relevant? 

Can you try with the new instructions:

```
docker run -d -v weights:/usr/src/app/weights -v datadb:/data/db/ -p 8008:8008 ghcr.io/nsarrazin/serge:latest
```
