### ISSUE TITLE
invalid model file '/usr/src/app/weights/ggml-alpaca-7B-q4_0.bin' (too old, regenerate your model files!)

### ISSUE THREAD

**Issue by gitwittidbit** [nsarrazin/serge#73]
Hi,

So I got this error.

I tried converting the model (7B) using the provided convert.py but that just doesn't do anything. No error message, no other output, no converted file.

Am I missing something obvious?

Thanks!

**Comment by robotdjman** [comment]
Did you download the model from the built in download script?

i.e.
`docker compose exec serge python3 /usr/src/app/api/utils/download.py tokenizer 7B`

**Comment by gitwittidbit** [comment]
Yes, the model and tokenizer are there. But Serge doesn‘t like the model :(

**Comment by gaby** [comment]
@gitwittidbit did you get it to work? Try the latest release, it has a download manager:

```
docker run -d -v weights:/usr/src/app/weights -v datadb:/data/db/ -p 8008:8008 ghcr.io/nsarrazin/serge:latest
```

**Comment by gitwittidbit** [comment]
Nah, but I had stopped trying.

With the new version - thanks for the pointer! - it's working now. Yay!
