### ISSUE TITLE
Docker build failing on new docker-compose.yaml:  [internal] load metadata for docker.io/library/gcc:11:

### ISSUE THREAD

**Issue by vnktsh** [nsarrazin/serge#76]
### Bug description

Docker build failing on new docker-compose.yaml

[+] Building 0.3s (2/4)
 => [internal] load build definition from Dockerfile                                                                                                                           
[+] Building 0.3s (4/4) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                           
 => => transferring dockerfile: 69B                                                                                                                                            
 => [internal] load .dockerignore                                                                                                                                              
 => => transferring context: 69B                                                                                                                                              
 => ERROR [internal] load metadata for docker.io/library/ubuntu:22.04                                                                                                          gcc:11                                                                                                                 
 > [internal] load metadata for docker.io/library/ubuntu:22.04:
 > [internal] load metadata for docker.io/library/gcc:11:
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: ``

### Steps to reproduce

Clean install.
Wipe out old dangling images, containers, networks etc.

1. Pull the latest code from `main` (sha [4047fbe](https://github.com/nsarrazin/serge/commit/4047fbe0be74405354ef8817c318c26f49ce6677))
2. Run `sudo docker compose build | optionally include [--no-cache]

### Environment Information

OS: Apple Silicon MacOS Ventura, M2 Max
sudo docker version
Client:
 Cloud integration: v1.0.31
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:35:19 2023
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.17.0 (99724)
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:31:28 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Relevant log output

```shell
[+] Building 0.3s (2/4)
 => [internal] load build definition from Dockerfile                                                                                                                            0.0s
[+] Building 0.3s (4/4) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                            0.0s
 => => transferring dockerfile: 69B                                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                               0.0s
 => => transferring context: 69B                                                                                                                                                0.0s
 => ERROR [internal] load metadata for docker.io/library/ubuntu:22.04                                                                                                           0.3s
 => ERROR [internal] load metadata for docker.io/library/gcc:11                                                                                                                 0.3s
------
 > [internal] load metadata for docker.io/library/ubuntu:22.04:
------
------
 > [internal] load metadata for docker.io/library/gcc:11:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: ``
```

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gaby** [comment]
Are behind a proxy? It's complaining about credentials

**Comment by Mattssn** [comment]
I am not sure if this will help, but if you are okay with not building the container you can remove the ```    build: 
      context: .
      dockerfile: Dockerfile
      target: dev```

section and add 

```image: ghcr.io/nsarrazin/serge:latest``` to the compose, this is what mine looks like, I have caddy labels added for my reverse proxy and its attached to my docker network, so that may vary for you. 

```
version: "3.9"

services:
  Serge:
    container_name: Serge
    image: ghcr.io/nsarrazin/serge:latest
    restart: unless-stopped
    volumes:
      - datadb:/data/db
      - weights:/usr/src/app/weights/
      - /etc/localtime:/etc/localtime:ro 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    labels:
      caddy: "serge.${DOMAIN}"
      caddy.reverse_proxy: "{{upstreams 8008}}"
    networks:
      - media```
