### ISSUE TITLE
A server error occurred. See below: main: seed = 1679852543

### ISSUE THREAD

**Issue by cpmilan** [nsarrazin/serge#77]
Hello,

I've installed Serge on a MacBook Pro with 16GB Memory. I'm trying to use the 13B Model, but get the following error for any message I send:

A server error occurred. See below: main: seed = 1679852543 llama_model_load: loading model from '/usr/src/app/weights/ggml-alpaca-13B-q4_0.bin' - please wait ... 
llama_model_load: n_vocab = 32000 
llama_model_load: n_ctx = 512 
llama_model_load: n_embd = 5120 
llama_model_load: n_mult = 256 
llama_model_load: n_head = 40 
llama_model_load: n_layer = 40 
llama_model_load: n_rot = 128 
llama_model_load: f16 = 2 
llama_model_load: n_ff = 13824 
llama_model_load: n_parts = 1 
llama_model_load: ggml ctx size = 8559.49 MB 
llama_model_load: memory_size = 800.00 MB, n_mem = 20480 
llama_model_load: loading model part 1/1 from '/usr/src/app/weights/ggml-alpaca-13B-q4_0.bin' 
llama_model_load: ............................................. done 
llama_model_load: model size = 7759.39 MB / num tensors = 363  
system_info: n_threads = 4 / 5 | AVX = 0 | AVX2 = 0 | AVX512 = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 0 | VSX = 0 |

(the message is interrupted and doesn't display anything else).

I've tried running the 7B model and it works fine.

Any idea what could be the issue here? Not enough Memory causing a crash perhaps?

Thank you

**Comment by dyno** [comment]
for whatever reason it's like the limit is only 2 GB on my machine, still trying to figure out how to raise the limit.
```
 docker stats --no-stream
CONTAINER ID   NAME                     CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
a37010b3570d   uildx_buildkit_default   0.00%     20.34MiB / 1.924GiB   1.03%     1.7GB / 4.18MB    1.83GB / 5.73GB   16
a704d1a6877b   erge-serge-1             0.00%     307.6MiB / 1.924GiB   15.61%    4.32GB / 8.95MB   4.25GB / 8.43GB   79
```

**Comment by FenarkSEC** [comment]
Have you tried with the newest ```main``` image available ? I used to get this error but seems to be fixed with the new release.

**Comment by nsarrazin** [comment]
Seems like this was an out of memory issue, so not really a bug we can fix.
