### ISSUE TITLE
Docker release versioning

### ISSUE THREAD

**Issue by mcsgroi** [nsarrazin/serge#78]
### Request
Release multiple Docker tags when the image gets updated so that different historical versions can still be consumed.

### Reason
Since development on this repo seems to be happening fairly quickly, it might be nice to keep previous versions of the Docker image package for 2 reasons:
1. If something breaks in latest, an old version can still be consumed successfully.
2. Updates aren't a requirement if someone wants to use an old version for some reason.

Obviously you can still do this right now by building the Docker image locally manually, but this would simplify it by just requiring a tag update for anyone pulling the image.

**Comment by gaby** [comment]
This is fixed by #79

**Comment by nsarrazin** [comment]
Yep totally agree! I see a PR open here #79 does this seem to do what you want ?

**Comment by mcsgroi** [comment]
Perfect, that's exactly what I was thinking. Thanks folks!

**Comment by nsarrazin** [comment]
@mcsgroi can you review that PR? would be great to have your opinion, then I'll approve.

**Comment by mcsgroi** [comment]
Sure 👍

**Comment by mcsgroi** [comment]
Since that is merged, I'm marking this as resolved.
