### ISSUE TITLE
Refactor the API

### ISSUE THREAD

**Issue by nsarrazin** [nsarrazin/serge#8]
Currently it's a bit of a mess with little to no structure.

 I'll be working on making things a bit more structured and expendable.

**Comment by LoopControl** [comment]
I'd love to see some separation or even the possibility to not run the model with this repo and instead just use the sveltekit app + mongo with an API of our choice.

For example, this project: https://github.com/oobabooga/text-generation-webui lets you run a number of models (including Llama / Alpaca) with things like 8bit and even the new GPTQ/4bit inference and also has an API that allows you to do generation without using their gradio interface.
