### ISSUE TITLE
no configuration file provided: not found

### ISSUE THREAD

**Issue by gerroon** [nsarrazin/serge#89]
### Bug description

I am able to run the initial docker image and login but I I am unable to download models

### Steps to reproduce

docker compose exec serge python3 /usr/src/app/api/utils/download.py tokenizer 7B

no configuration file provided: not found

### Environment Information

Docker 20
Debian Testing

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by FenarkSEC** [comment]
You must be in the directory where you cloned the repo, otherwise docker compose will return ```no configuration file provided: not found```.
