### ISSUE TITLE
As an api image builder, I would like to ignore *.bin.old files as well. 

### ISSUE THREAD

**Issue by y12studio** [nsarrazin/serge#9]
README: 
> The old weights will be renamed to *.bin.old and the new weights will be named *.bin.

https://github.com/nsarrazin/serge/blob/b5ff9d154142ca918347604e0fd89dd3b003fab0/api/.dockerignore#L1

**Comment by nsarrazin** [comment]
Ah, good catch, that's why the build context got so big when I rebuilt this from scratch. Will fix it
