### ISSUE TITLE
llama.cpp not cloning in Docker

### ISSUE THREAD

**Issue by countnoobula** [nsarrazin/serge#93]
### Bug description

After following the setup instructions using a fresh installation of Kubuntu on my laptop with docker from the official repository, I experience the error message when attempting to send a query.

It is worth noting that this does not appear to be an issue in Manjaro [tested that in a VM], but does experience this issue in Ubuntu on a VM

### Steps to reproduce

1. Fresh install of Ubuntu 22.10
2. Install docker from official apt repositories
3. docker compose up --build -d
4. docker compose exec serge python3 /usr/src/app/api/utils/download.py tokenizer 7B
5. Access http://localhost:8008
6. Submit query, UI glitches, refresh page and see the error

### Environment Information

Docker 23.0.2 build 569dd73 (installed from official apt repositories)
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.10
DISTRIB_CODENAME=kinetic
DISTRIB_DESCRIPTION="Ubuntu 22.10"

### Screenshots

![image](https://user-images.githubusercontent.com/540113/228253072-1537b026-0e1f-4bc2-94e8-98e3a4de3fbf.png)

### Relevant log output

```shell
serge-serge-1  | ./compile.sh: line 5: cd: /usr/src/app/llama.cpp: No such file or directory
serge-serge-1  | make: *** No targets specified and no makefile found.  Stop.
serge-serge-1  | mv: cannot stat 'main': No such file or directory
serge-serge-1  | INFO:     Started server process [14]
serge-serge-1  | INFO:     Waiting for application startup.
serge-serge-1  | INFO:  main    initializing database connection
serge-serge-1  | INFO:  main    initializing models
serge-serge-1  | INFO:     Application startup complete.
serge-serge-1  | INFO:     Uvicorn running on http://0.0.0.0:8008 (Press CTRL+C to quit)
serge-serge-1  | INFO:  main    models are ready
serge-serge-1  | ERROR: main    [Errno 2] No such file or directory
```
[serge-logs-2803.log](https://github.com/nsarrazin/serge/files/11090302/serge-logs-2803.log)

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gaby** [comment]
@countnoobula Can you add the container logs?

**Comment by countnoobula** [comment]
@gaby I have attached logs by running 

```shell
docker compose up > serge-logs-2803.log
```

**Comment by countnoobula** [comment]
If I docker exec into the serge container and run the following, it works:

```
git clone https://github.com/ggerganov/llama.cpp.git
./compile.sh
./deploy.sh
```

This would appear to be a cloning issue. I should mention I experienced similar issues in WSL2 with respect to github.com not resolving inside the container which could be a local issue, but I think this would be useful to add to the troubleshooting documentation.

**Comment by countnoobula** [comment]
Thank you so much for your patience. I had adapted the code from https://github.com/nsarrazin/serge/issues/63#issuecomment-1483925262 in order to fix my restart loop. I'll make a note in that issue regarding the git clone line that can be easily omitted
